version: '2'

services:

  devmaster:
    image: devshop/devmaster:xdebug
    ports:
      - 80:80
    hostname: dev.local.computer
    links:
      - database
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      AEGIR_MAKEFILE: https://raw.githubusercontent.com/opendevshop/devshop/1.x/build-devmaster.make
      AEGIR_PROFILE: devmaster
      AEGIR_VERSION: 1.x
      AEGIR_HOSTMASTER_ROOT: /var/aegir/devmaster-1.x
      XDEBUG_CONFIG: "remote_host=172.17.0.1 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=devshop.local.computer"
    volumes:
      - ./projects:/var/aegir/projects:Z

  database:
    image: mariadb
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    command: mysqld --innodb-large-prefix --innodb-file-format=barracuda --innodb-file-per-table

  admin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - 8080:80

  selenium:
    image: selenium/standalone-chrome-debug:3.1.0-astatine
    links:
     - "devmaster:master.prompt.dev.local.computer"
    ports:
      - 4444:4444
      - 5900:5900
